# Gems
gems: [jekyll-paginate, jekyll-sitemap, jekyll-gist, jekyll-seo-tag, jekyll-redirect-from]

# Site settings
title: Tech Stack
email: yunxinyi+github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technical stack for one nerd.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://oxnz.github.io" # the base hostname & protocol for your site
twitter_username: yunxinyi
github_username:  oxnz

# Build settings
markdown: kramdown

# Conversion
timezone: Asia/Shanghai
excerpt_separator: <!--more-->

# Pagination
paginate: 10

# Sass
sass:
  style: compressed

# View
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      hreflangs: "en"
      author:
        login: oxnz
        email: yunxinyi@gmail.com
        display_name: oxnz
      categories: "misc"
      tags: "misc"
  -
    scope:
      path: ""
      type: "pages"
    values:
      hreflangs: "en"
      author:
        login: oxnz
        email: yunxinyi@gmail.com
        display_name: oxnz
